# This is a GitHub workflow YAML file
# see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#
# For every push on a pull request, it
# - creates or updates a comment about potential pr impact on performance metrics
# Read more in
# - https://github.com/jsenv/performance-impact
#
# If you want to update this file it's recommended to use a YAML validator
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# configured to validate with https://json.schemastore.org/github-workflow.json

name: performance_impact

on: pull_request

jobs:
  pr_impact:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [16.14.2]
    runs-on: ${{ matrix.os }}
    name: performance impact
    steps:
      - name: Setup git
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install node modules
        run: npm install
      - name: Setup playwright
        run: npm run playwright-install
      - name: Setup certificate
        run: npm run certificate-install
      - name: Report performance impact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./.github/workflows/pr_impact/report_performance_impact.mjs
