name: pr-impact

on:
  pull_request:
    # In theory it would be more efficient to enable this workflow only
    # if certain file changes (the one that could impact dist/ files)
    # In practice humans will wonder why the workflow did not run.
    # paths:
    #   - "index.js"
    #   - "src/**"

jobs:
  pr-impact:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.17.0]
    runs-on: ${{ matrix.os }}
    name: pr impact
    env:
      CI: true
    steps:
      - name: Setup git
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup npm
        run: npm install
      - name: Report file size impact
        run: node ./.github/workflows/pr-impact/report-size-impact.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Report lighthouse impact
        run: node ./.github/workflows/pr-impact/report-lighthouse-impact.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
